# Generated by Django 6.0.7 on 2026-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='scope',
            field=models.CharField(choices=[('knowledge_base', 'Knowledge Base (training material)'), ('customer_history', 'Customer service history'), ('engineer_history', 'Full technical history (for an engineer preparing a job)')], max_length=32),
        ),
    ]
