# Generated by Django 6.0.7 on 2026-08-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_accesscode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
