# Generated by Django 6.0.7 on 2026-07-28 05:59

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcomment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tickets.models.ticket_comment_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='video_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
