# Generated by Django 6.0.7 on 2026-08-03 09:30

import django.db.models.deletion
import tickets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcomment_video_ticketcomment_video_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_performed', models.TextField(help_text='What was actually done on site, in detail.')),
                ('root_cause', models.TextField(blank=True, help_text='Why the problem happened.')),
                ('parts_used', models.TextField(blank=True, help_text='Parts replaced or consumed.')),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only observations. Never shown to the customer.')),
                ('service_video', models.FileField(blank=True, help_text='On-site recording. Internal only -- used for training, never sent to the customer.', max_length=255, null=True, upload_to=tickets.models.service_report_video_upload_path)),
                ('service_video_filename', models.CharField(blank=True, max_length=255)),
                ('customer_summary', models.TextField(blank=True, help_text='Short, plain-language summary written by the service layer for the customer.')),
                ('shared_with_customer_at', models.DateTimeField(blank=True, help_text='Set when the summary is released. Until then the customer sees nothing.', null=True)),
                ('include_in_knowledge_base', models.BooleanField(default=False, help_text="Make this report's video available as internal training material.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to=settings.AUTH_USER_MODEL)),
                ('summarised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports_summarised', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_report', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
