# Generated by Django 6.0.7 on 2026-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_servicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='video_title',
            field=models.CharField(blank=True, help_text="What the recording shows, e.g. 'Replacing a fuser unit on an HP M404'.", max_length=200),
        ),
    ]
