# Generated by Django 6.0.7 on 2026-08-03 20:42

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_servicereport_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tickets.models.ticket_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tickets.models.ticket_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='ticket',
            name='video_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
