# Generated by Django 6.0.7 on 2026-07-10 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="e.g. 'ticket.assigned', 'staff.role_changed'", max_length=100)),
                ('target_type', models.CharField(blank=True, help_text='Model name of the affected object', max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, help_text='Null for platform-level (Soori Admin) actions with no single tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='audit_audit_client__7338ba_idx')],
            },
        ),
    ]
