# Generated by Django 6.0.7 on 2026-07-10 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClientProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'sub_client'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sub_client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SupportStaffProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'support_staff'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_role', models.CharField(choices=[('agent', 'Agent'), ('senior_agent', 'Senior Agent'), ('supervisor', 'Supervisor')], default='agent', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active_agent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(help_text='The Soori Admin who onboarded this client.', limit_choices_to={'role': 'soori_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
