# Generated by Django 6.0.7 on 2026-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_document',
            field=models.FileField(blank=True, help_text='Scanned registration certificate or equivalent proof document.', null=True, upload_to='client_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_registration_number',
            field=models.CharField(blank=True, help_text='PAN, VAT, GSTIN, or equivalent business tax registration number.', max_length=100),
        ),
    ]
