# Generated by Django 6.0.7 on 2026-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_address_client_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_period',
            field=models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='1_month', help_text='Billing term. Drives subscription_end -- see ClientSerializer.', max_length=20),
        ),
    ]
