# Generated by Django 6.0.7 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_subscription_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclientprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='subscription_period',
            field=models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='1_month', max_length=20),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='tax_document',
            field=models.FileField(blank=True, help_text='Scanned registration certificate or equivalent proof document.', max_length=255, null=True, upload_to='subclient_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='subclientprofile',
            name='tax_registration_number',
            field=models.CharField(blank=True, help_text='PAN, VAT, GSTIN, or equivalent business tax registration number.', max_length=100),
        ),
    ]
