# Generated by Django 6.0.7 on 2026-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_subclientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
