# Generated by Django 6.0.7 on 2026-08-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_supportstaffprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclientprofile',
            name='service_area',
            field=models.CharField(blank=True, help_text="City or area this customer is located in, e.g. 'Kathmandu'.", max_length=120),
        ),
        migrations.AddField(
            model_name='supportstaffprofile',
            name='service_area',
            field=models.CharField(blank=True, help_text="City or area this engineer covers, e.g. 'Kathmandu'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='supportstaffprofile',
            name='staff_role',
            field=models.CharField(choices=[('service_department', 'Service Department'), ('field_engineer', 'Field Engineer')], default='service_department', max_length=50),
        ),
    ]
