# Generated by Django 6.0.7 on 2026-08-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_old_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaffprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='clients.staffrole'),
        ),
    ]
